// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4cxn_MFR965ztb5ZIEgWoJElT2sx1kyY',
    appId: '1:361310258455:web:5029d136e2b54b0880e352',
    messagingSenderId: '361310258455',
    projectId: 'project-1-e9af1',
    authDomain: 'project-1-e9af1.firebaseapp.com',
    storageBucket: 'project-1-e9af1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCarksWUly4HsuQw3b1iBUY66kKZTM_dtI',
    appId: '1:361310258455:android:04ccc48875c7e00980e352',
    messagingSenderId: '361310258455',
    projectId: 'project-1-e9af1',
    storageBucket: 'project-1-e9af1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN8WN-SnuHvuODQo68FjG-tvYp-ywprGI',
    appId: '1:361310258455:ios:190d5c5eb905482580e352',
    messagingSenderId: '361310258455',
    projectId: 'project-1-e9af1',
    storageBucket: 'project-1-e9af1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN8WN-SnuHvuODQo68FjG-tvYp-ywprGI',
    appId: '1:361310258455:ios:190d5c5eb905482580e352',
    messagingSenderId: '361310258455',
    projectId: 'project-1-e9af1',
    storageBucket: 'project-1-e9af1.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4cxn_MFR965ztb5ZIEgWoJElT2sx1kyY',
    appId: '1:361310258455:web:939bb91163313b5f80e352',
    messagingSenderId: '361310258455',
    projectId: 'project-1-e9af1',
    authDomain: 'project-1-e9af1.firebaseapp.com',
    storageBucket: 'project-1-e9af1.firebasestorage.app',
  );
}
